services:
  app:
    image: mysociety/composite_uk_imd:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/composite_uk_imd      
    volumes:
      - ./:/workspaces/composite_uk_imd/