title: "{{page_title}}"
slug: "{{page_title.lower().replace(' ', '_')}}"
notebooks:
  - readme
parameters:
  page_title: "Methodology and Analysis"
options:
  rerun: true
  hide_input: true
upload:
  jekyll:
  readme: